#!/bin/bash

# RR Enterprises - Vercel Deployment Script
# This script helps deploy backend and frontend to Vercel

echo "🚀 RR ENTERPRISES - VERCEL DEPLOYMENT"
echo "======================================"
echo ""

# Parse Neon connection string
DB_HOST="ep-fancy-snow-aib3um5n-pooler.c-4.us-east-1.aws.neon.tech"
DB_USER="neondb_owner"
DB_PASS="npg_w7mPGtrWo8jF"
DB_NAME="neondb"
DB_PORT="5432"

echo "✅ Database imported successfully to Neon"
echo ""
echo "📦 STEP 1: Deploy Backend"
echo "=========================="
echo ""
echo "Run these commands:"
echo ""
echo "cd backend"
echo "npx vercel --prod"
echo ""
echo "When prompted:"
echo "  - Set up and deploy? Y"
echo "  - Which scope? [Your account]"
echo "  - Link to existing project? N"
echo "  - Project name? rr-enterprises-backend"
echo "  - Directory? ./"
echo "  - Override settings? N"
echo ""
echo "After deployment, go to Vercel Dashboard and add these environment variables:"
echo ""
echo "DB_HOST=$DB_HOST"
echo "DB_PORT=$DB_PORT"
echo "DB_USER=$DB_USER"
echo "DB_PASS=$DB_PASS"
echo "DB_NAME=$DB_NAME"
echo "JWT_SECRET=your-random-secret-key-change-this"
echo "NODE_ENV=production"
echo ""
echo "Then redeploy: npx vercel --prod"
echo ""
echo "================================"
echo "📱 STEP 2: Deploy Frontend"
echo "================================"
echo ""
echo "After backend is deployed and you have the URL, run:"
echo ""
echo "cd ../frontend"
echo ""
echo "Create .env.production file:"
echo "echo 'REACT_APP_API_URL=https://your-backend-url.vercel.app' > .env.production"
echo ""
echo "Then deploy:"
echo "npx vercel --prod"
echo ""
echo "When prompted:"
echo "  - Set up and deploy? Y"
echo "  - Which scope? [Your account]"
echo "  - Link to existing project? N"
echo "  - Project name? rr-enterprises-frontend"
echo "  - Directory? ./"
echo "  - Override settings? N"
echo ""
echo "================================"
echo "🔒 STEP 3: Update CORS"
echo "================================"
echo ""
echo "After frontend is deployed, update backend/app.js CORS:"
echo "Add your frontend URL to the cors whitelist, then redeploy backend"
echo ""
echo "================================"
echo "✅ DEPLOYMENT COMPLETE!"
echo "================================"
echo ""
echo "Your app will be live at:"
echo "- Backend: https://rr-enterprises-backend.vercel.app"
echo "- Frontend: https://rr-enterprises-frontend.vercel.app"
echo ""
echo "📖 For detailed instructions, see: VERCEL_DEPLOYMENT_GUIDE.md"
